### PR TITLE
fix: preserve stream parameter in CompletionRequest

### LINKED ISSUE #46: `stream` Parameter Omission in Chat Completion Requests
The `DefaultOpenAiClient` in the `openai4j` project does not preserve the `stream` parameter in chat completion requests, even when explicitly set to `false`. This omission causes compatibility issues with LLM providers that interpret the absence of a `stream` parameter as `stream=true`. This behavior results in unexpected streaming responses, which cannot be disabled.

### Problem Details

In the `DefaultOpenAiClient.chatCompletion()` method, the request is modified, but the `stream` parameter is discarded, even if explicitly set to `false`. This makes it impossible to disable streaming for LLM providers that require `"stream": false` in the JSON payload.

#### Relevant Code Section:
```java
@Override
public SyncOrAsyncOrStreaming<ChatCompletionResponse> chatCompletion(OpenAiClientContext context,
    ChatCompletionRequest request) {
    ChatCompletionRequest syncRequest = ChatCompletionRequest.builder().from(request).stream(null).build();

    return new RequestExecutor<>(
            openAiApi.chatCompletions(context.headers(), syncRequest, apiVersion),
            r -> r,
            okHttpClient,
            formatUrl("chat/completions"),
            () -> ChatCompletionRequest.builder().from(request).stream(true).build(),
            ChatCompletionResponse.class,
            r -> r,
            logStreamingResponses
    );
}
```

As shown above, the `stream` parameter is set to `null` in the `syncRequest`, causing it to be omitted in the final payload.

### Reproduction Steps

1. Create a `ChatCompletionRequest` object with `.stream(false)` explicitly set.
2. Send the request through `DefaultOpenAiClient`.
3. Observe the generated JSON request payload sent to the LLM provider.
4. Notice that the `stream` parameter is completely absent from the JSON, leading to unintended streaming behavior.

#### Example Test Case:
```java
@Test
void demonstrateStreamingForced() throws Exception {
    // Setup a mock server and client
    DefaultOpenAiClient client = DefaultOpenAiClient.builder()
            .baseUrl(mockWebServer.url("/").toString())
            .openAiApiKey("test-key")
            .build();

    // Create a ChatCompletionRequest with stream set to false
    ChatCompletionRequest request = ChatCompletionRequest.builder()
            .model("random-model")
            .addUserMessage("Hello")
            .stream(false)
            .build();

    client.chatCompletion(request).execute();

    // Capture and inspect the outgoing request
    RecordedRequest recordedRequest = mockWebServer.takeRequest();
    String requestBody = recordedRequest.getBody().readUtf8();

    // Verify the stream parameter
    JsonNode jsonNode = objectMapper.readTree(requestBody);
    assertTrue(jsonNode.has("stream"), "Request should contain stream parameter but isn't present");
}
```

#### Observed Behavior:
The `stream` parameter is omitted from the JSON payload entirely:
```json
{
  "model": "random-model",
  "messages": [{"role":"user","content":"Hello"}]
}
```

#### Expected Behavior:
The `stream` parameter should be explicitly included in the payload when set to `false`:
```json
{
  "model": "random-model",
  "messages": [{"role":"user","content":"Hello"}],
  "stream": false
}
```

### Affected Scenarios

This issue is critical for:
- Local LLM deployments that require explicit `stream` settings.
- Custom OpenAI-compatible APIs that interpret missing parameters as `stream=true`.
- Use cases where streaming must be explicitly disabled to prevent unintended behavior.

### Workaround
Currently, the only solution involves intercepting and modifying requests manually or introducing proxy layers, which adds unnecessary complexity.

### Proposed Solution
Update `DefaultOpenAiClient` to propagate the `stream` parameter as-is, preserving its original value from the request object. If `stream` is explicitly set to `false`, it should be reflected in the final JSON payload.

---

#### Environment Details:
- **OpenAi4j version:** [Specify the version you are using]
- **LLM(s):** OpenAI-compatible APIs on LM Studio
- **Java version:** 21

#### Additional Context:
This behavior was originally reported in the LangChain4j repository (https://github.com/langchain4j/langchain4j/issues/2182) and identified as an issue to be addressed in `openai4j`.

### PR DESCRIPTION
**Pull request by keyboardsamurai**
### Problem
The `stream` parameter was omitted from requests, causing unexpected streaming behavior.

### Fix
Ensured the `stream` parameter is preserved in CompletionRequest and ChatCompletionRequest.

### Tests
Added unit tests to verify that the `stream` parameter is respected for both `true` and `false` values.

Closes #46

### CODE REVIEW

File: src/test/java/dev/ai4j/openai4j/completion/CompletionTest.java [hunk 1]
```diff
@@ -41,4 +48,171 @@ void testCustomizableApi() {
...
+        // Assert the responses are not null and contain valid choices
+        assertThat(responseForStreamFalse).isNotNull();
+        assertThat(responseForStreamFalse.choices()).isNotEmpty();
+        assertThat(responseForStreamFalse.text()).isNotEmpty();
+
+        assertThat(responseForStreamTrue).isNotNull();
+        assertThat(responseForStreamTrue.choices()).isNotEmpty();
+        assertThat(responseForStreamTrue.text()).isNotEmpty();
+
+        // Optionally log for manual verification
```
Comment (langchain4j) [inline src/test/java/dev/ai4j/openai4j/completion/CompletionTest.java:80]: please remove `souts`

File: src/test/java/dev/ai4j/openai4j/completion/CompletionTest.java [hunk 2]
```diff
@@ -41,4 +48,171 @@ void testCustomizableApi() {
 
         assertThat(response.text()).containsIgnoringCase("hello world");
     }
+
+
+    @Test
+    void shouldPreserveStreamParameter() {
```
Comment (langchain4j) [inline src/test/java/dev/ai4j/openai4j/completion/CompletionTest.java:54]: How does this test test anything? First of all, it is testing completion, but the changes were done in chat completion

**Review by ghost — COMMENTED** [review]
@keyboardsamurai did you generate tests with LLM? Most of them make no sense to me

**Comment by keyboardsamurai** [comment]
Thanks for the input mate. I've pushed an update. Let me know if it achieves the goal of making sense this time.

**Review by ai-for-java — APPROVED** [review]
@keyboardsamurai thank you!
